name: mahattaty
description: "A Train Booking Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_riverpod: ^2.5.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  cloud_firestore: ^5.4.4
  skeletonizer: ^1.4.2
  transparent_image: ^2.0.1
  syncfusion_flutter_datepicker: ^27.1.51
  qr_flutter: ^4.1.0
  device_preview: ^1.2.0
  arabic_numbers: ^1.0.0
  connectivity_plus: ^6.0.5
  flutter_connectivity: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/icons/

