// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfucmDUCKa6X7Z3X7QRRYZP5kLmBznMIQ',
    appId: '1:750210986338:android:bf6ab16001511441ac7c3b',
    messagingSenderId: '750210986338',
    projectId: 'mahattaty',
    storageBucket: 'mahattaty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhllVODp4sFIP-yjRX0Ivc672ARC2LBXk',
    appId: '1:750210986338:ios:b003b230165a0268ac7c3b',
    messagingSenderId: '750210986338',
    projectId: 'mahattaty',
    storageBucket: 'mahattaty.appspot.com',
    androidClientId: '750210986338-a9jdvles6mhlnkvr65c9gdneckuue0s2.apps.googleusercontent.com',
    iosClientId: '750210986338-hmnj22iv8t8dkh9ecdl4duavljrm8dus.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahattaty',
  );
}
